insert into ACT_GE_PROPERTY values ('variable.schema.version', '6.3.0.1', 1);
insert into ACT_GE_PROPERTY values ('task.schema.version', '6.3.0.1', 1);
insert into ACT_GE_PROPERTY values ('job.schema.version', '6.3.0.1', 1);
insert into ACT_GE_PROPERTY values ('identitylink.schema.version', '6.3.0.1', 1);
insert into ACT_ID_PROPERTY values ('schema.version', '6.3.0.1', 1);
insert into ACT_GE_PROPERTY values ('common.schema.version', '6.3.0.1', 1);
insert into ACT_GE_PROPERTY values ('next.dbid', '1', 1);
insert into ACT_GE_PROPERTY values ('schema.version', '6.3.0.1', 1);
insert into ACT_GE_PROPERTY values ('schema.history', 'create(6.3.0.1)', 1);